### ISSUE TITLE
missing react & react-dom as dependencies

### ISSUE THREAD

**Issue by jerrylau91** [christianalfoni/react-simple-flex#2]
As mentioned above.

**Comment by Guria** [comment]
It shouldn't be `dependencies`, but only `peerDependencies`. It is absent currently too, but it is not much problem since your project has direct deps on `react` and `react-dom` already.

**Comment by christianalfoni** [comment]
Yeah, it often causes more problems than benefits. Giving NPM warning etc. Also have to keep updating the versions, so just a lot of hassle. If it was doing some crazy stuff I would need to use react version reference to ensure compatability, but there is nothing special going on here so will very likely work with any updates of React for a long long time.

Also very unlikely that you install this lib without already having React and React-Dom, and if you do you get a warning that it is missing anyways :)

**Comment by christianalfoni** [comment]
But thanks for taking the time to create the issue! And let me know if you think I am crazy not to add it ;-)

**Comment by jerrylau91** [comment]
haha understood @christianalfoni , fair enough !

**Comment by jerrylau91** [comment]
@Guria agreed!
