### ISSUE TITLE
latest react gives error on unknown props

### ISSUE THREAD

**Issue by nireak** [christianalfoni/react-simple-flex#4]
react 15.2.0 added 
_Add warning for unknown properties on DOM elements_

this introduces a lot of warnings in console like

`Warning: Unknown prop`column`on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop`

`Warning: Unknown prop`grow`on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop`

`Warning: Unknown prop`alignVertical`on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop`

`Warning: Unknown prop`row`on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop`

Thank you

**Comment by christianalfoni** [comment]
Ah, yes, thanks for reporting. This should be fixed now :)
